/* eslint-disable @next/next/no-page-custom-font */
// import { Inter } from "next/font/google";
import Layout from "@/layout/Layout";
import MainLayout from "@/layout/MainLayout";
import "@/assets/scss/style.scss";
import { Toaster } from "react-hot-toast";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <head>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Layout>
          <Toaster />
          <MainLayout>{children}</MainLayout>
        </Layout>
      </body>
    </html>
  );
}
